name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
          
      - uses: actions/setup-node@v3
        with:
            node-version: 16.x
            
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
                cd organize-clone-backend
                git pull
                npm install
                node ace build --production
                cp .env.example build/.env
